<?php

namespace AppBundle\Repository;

/**
 * BestellingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BestellingRepository extends \Doctrine\ORM\EntityRepository
{
}
