<?php

namespace AppBundle\Repository;

/**
 * BestelopdrachtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BestelopdrachtRepository extends \Doctrine\ORM\EntityRepository
{
}
