<?php

namespace AppBundle\Repository;

/**
 * LeverancierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeverancierRepository extends \Doctrine\ORM\EntityRepository
{
}
