<?php

namespace AppBundle\Repository;

/**
 * NaamLeverancierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class naamleverancierRepository extends \Doctrine\ORM\EntityRepository
{
}
