<?php

namespace AppBundle\Repository;

/**
 * OntvangengoederenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OntvangengoederenRepository extends \Doctrine\ORM\EntityRepository
{
}
