<?php

namespace AppBundle\Repository;

/**
 * RetourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetourRepository extends \Doctrine\ORM\EntityRepository
{
}
