# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    role_hierarchy:
        ROLE_ADMIN:      [ROLE_USER, ROLE_ADMIN, ROLE_INKOPER]
        ROLE_USER:       [ROLE_MAGAZIJNMEESTER]

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$13$cX6iwF2NpXSHEQziWHha6eeRbhSnS44bcRcqMturn1E4M2rsiuWn6
                        roles: 'ROLE_ADMIN'
                    inkoper:
                        password: $2y$13$SHqEutCankUz3m6GNUWTjuXMasvPG6CLP6byJ3RaBM7qZYW6opRdy
                        roles: 'ROLE_ADMIN'
                    magazijnmeester:
                        password: $2y$13$.mz77fGlPalMSQt8GesBCeP7Cl9DC7.bqmmP3FXpTYlY/8CwHv1Ba
                        roles: 'ROLE_USER'
                    beheerder:
                        password: $2y$13$7kQTtiDC.sYuw98bKM1x0e35ksWMLYwGEewNpCszWR4UkQbWv/kbO
                        roles: 'ROLE_ADMIN'
                    applicatiebeheerder:
                        password: $2y$13$w98dqikHShspKyVbAL3bV.TWAKH8v4USY.wbV.izOH4ujBoatyDDS
                        roles: 'ROLE_ADMIN'
                    hoofdfinanciën:
                        password: $2y$13$iG93CcNQa7syQu/iSkvR..bR9FE5jAqkA6LdwoHjxqLnYist1BAoO
                        roles: 'ROLE_ADMIN'
                    ontwikkelaar:
                        password: $2y$13$1cCTG9tVTllwzesyk.L4nuJn.8ds52QabPHRyx8q.vHI0Npi1Cjey
                        roles: 'ROLE_ADMIN'
                    reparateur:
                        password: $2y$13$GOn41O2.MN6DxDKWy65Flet97crUn3Fe5/80VUK5cf8gL9k18awDW
                        roles: 'ROLE_ADMIN'
                    expediteur:
                        password: $2y$13$0yzHe5gUtOsCpCWvTem4oe2kZg3j4.MhiC6LxwDfESKMvKdBH3qTm
                        roles: 'ROLE_ADMIN'
                    

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt


    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/*, roles: ROLE_USER }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout: true
