# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    role_hierarchy:
        ROLE_ADMIN:      [ROLE_USER, ROLE_ADMIN, ROLE_MAGAZIJNMEESTER]

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$13$cX6iwF2NpXSHEQziWHha6eeRbhSnS44bcRcqMturn1E4M2rsiuWn6
                        roles: 'ROLE_ADMIN'
                    inkoper:
                        password: $2y$13$SHqEutCankUz3m6GNUWTjuXMasvPG6CLP6byJ3RaBM7qZYW6opRdy
                        roles: 'ROLE_ADMIN'
                    magazijnmeester:
                        password: $2y$13$.mz77fGlPalMSQt8GesBCeP7Cl9DC7.bqmmP3FXpTYlY/8CwHv1Ba
                        roles: 'ROLE_MAGAZIJNMEESTER'

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt


    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/*, roles: ROLE_USER }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout: true
